use_frameworks!

platform :ios, '9.0'

target 'PLCategoryPubKit_Example' do
  pod 'PLCategoryPubKit', :path => '../'

  target 'PLCategoryPubKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
